### ISSUE TITLE
Enable multi-repo support (esp. dotnet/coreclr repo queries)

### ISSUE THREAD

**Issue by karelz** [karelz/GitHubIssues#2]
- [x] 1. Replace all hardcoded links to issues/queries - corefx (fixed in #50)
- [x] 2. Replace repo in the HTML template (fixed in #50)
- [x] 3. Report on multiple issue files (from corefx and coreclr repos) (fixed in #50)
- [x] 4. Set up downloading coreclr data - depends on #3

**Comment by karelz** [comment]
Fixed by #50.
